name: RateTheLandlord CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-be:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint backend
        run: |
          cd backend
          npm install
          npm run lint

  lint-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint frontend
        run: |
          cd frontend
          npm install
          npm run lint

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint-be, lint-fe]

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Docker-Compose build
        run: docker-compose build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [lint-be, build-be, lint-fe, build-fe]

  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  # - name: Deploy
  #   if: github.ref == 'refs/heads/main'
  #   uses: garygrossgarten/github-action-ssh@release
  #   with:
  #     command: sh deploy.sh
  #     host: ${{ secrets.HOST }}
  #     username: ${{ secrets.USER }}
  #     password: ${{ secrets.PASS }}
